swagger: "2.0"
info:
  title: dp-collection-api
  description: "An API for collection management"
  version: 1.0.0
  license:
    name: "Open Government Licence v3.0"
    url: "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
basePath: "/v1"
schemes:
  - http
tags:
paths:

responses:
  InternalError:
    description: "Failed to process the request due to an internal error"

