// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dp-collection-api/api"
	"github.com/ONSdigital/dp-collection-api/collections"
	"github.com/ONSdigital/dp-collection-api/models"
	"sync"
)

// Ensure, that CollectionStoreMock does implement api.CollectionStore.
// If this is not the case, regenerate this file with moq.
var _ api.CollectionStore = &CollectionStoreMock{}

// CollectionStoreMock is a mock implementation of api.CollectionStore.
//
//     func TestSomethingThatUsesCollectionStore(t *testing.T) {
//
//         // make and configure a mocked api.CollectionStore
//         mockedCollectionStore := &CollectionStoreMock{
//             GetCollectionsFunc: func(ctx context.Context, queryParams collections.QueryParams) ([]models.Collection, int, error) {
// 	               panic("mock out the GetCollections method")
//             },
//         }
//
//         // use mockedCollectionStore in code that requires api.CollectionStore
//         // and then make assertions.
//
//     }
type CollectionStoreMock struct {
	// GetCollectionsFunc mocks the GetCollections method.
	GetCollectionsFunc func(ctx context.Context, queryParams collections.QueryParams) ([]models.Collection, int, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetCollections holds details about calls to the GetCollections method.
		GetCollections []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// QueryParams is the queryParams argument value.
			QueryParams collections.QueryParams
		}
	}
	lockGetCollections sync.RWMutex
}

// GetCollections calls GetCollectionsFunc.
func (mock *CollectionStoreMock) GetCollections(ctx context.Context, queryParams collections.QueryParams) ([]models.Collection, int, error) {
	if mock.GetCollectionsFunc == nil {
		panic("CollectionStoreMock.GetCollectionsFunc: method is nil but CollectionStore.GetCollections was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		QueryParams collections.QueryParams
	}{
		Ctx:         ctx,
		QueryParams: queryParams,
	}
	mock.lockGetCollections.Lock()
	mock.calls.GetCollections = append(mock.calls.GetCollections, callInfo)
	mock.lockGetCollections.Unlock()
	return mock.GetCollectionsFunc(ctx, queryParams)
}

// GetCollectionsCalls gets all the calls that were made to GetCollections.
// Check the length with:
//     len(mockedCollectionStore.GetCollectionsCalls())
func (mock *CollectionStoreMock) GetCollectionsCalls() []struct {
	Ctx         context.Context
	QueryParams collections.QueryParams
} {
	var calls []struct {
		Ctx         context.Context
		QueryParams collections.QueryParams
	}
	mock.lockGetCollections.RLock()
	calls = mock.calls.GetCollections
	mock.lockGetCollections.RUnlock()
	return calls
}
