---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.16.4

inputs:
  - name: dp-collection-api

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-collection-api/ci/scripts/build.sh
